### ISSUE TITLE
High memory consumption compared to native.

### ISSUE THREAD

**Issue by juj** [juj/emscripten-scummvm#19]
In mobile Nexus 7 tablet device with Android 4.2.2 and Firefox 21.0:

Starting up, baseline Firefox takes up 100MB of memory.
While playing Monkey 1, Firefox consumes 200MB - 261 MB of memory.
While playing Sam & Max 1, Firefox consumes 271MB - 290 MB of memory.

The same device with the Opera 14.0.1074.56201 browser:
baseline: 108 MB,
Monkey 1: 221 MB (in two different processes)

The same device with the Chrome 27.0.1453.90 browser:
baseline: 72MB
Monkey 1: 189 MB

In native Win32 exe:
baseline: 8 MB,
while playing Monkey 1: 20MB,
Sam & Max 1: 21MB.

In both games, Firefox gives about 8-10x memory consumption compared to native.

**Comment by trevor403** [comment]
Transpiling C++ to JavaScript (which runs in its own compiling engine above native) is extremely inefficient. You will see a loss in memory and instruction cycle efficiency due to the overhead of the JavaScript engine.

**Comment by juj** [comment]
Oh, this was a placeholder to store some profiling data, not relevant any more.
