### ISSUE TITLE
 fatal error: SDL.h: No such file or directory

### ISSUE THREAD

**Issue by burnhamup** [juj/emscripten-scummvm#26]
I've been trying to follow the tutorial, and I've been running into a lot of problems. 

I think I've done everything correctly in steps 1-7. I resolved some issues by using the full path name instead of `~`. 

Trying to run `emmake make` results in the following output:

```
    C++      backends/platform/sdl/sdl.o
In file included from ./backends/platform/sdl/sdl.h:26:0,
                 from backends/platform/sdl/sdl.cpp:31:
./backends/platform/sdl/sdl-sys.h:55:17: fatal error: SDL.h: No such file or directory
 #include <SDL.h>
                 ^
compilation terminated.
make: *** [backends/platform/sdl/sdl.o] Error 1
```

I'm not sure how to debug this. I'm on a fresh install of Ubuntu 14.04, and might be missing packages. I think I'm supposed to load the SDL.h that is included in emscripten, but don't know how to point it there. I've edited the copy of sdl-config in the emscripten folder and ran configure with the sdl argument pointing t the emscripten folder as well.

**Comment by juj** [comment]
Hmm not sure, but off the top of my head, trying to change the include line to say `#include <SDL/SDL.h>` might have some effect - the Emscripten provided tests use that form at least: https://github.com/kripken/emscripten/blob/master/tests/hello_world_sdl.cpp#L2 . I can't recall what is different in the builds I did as to why the current form worked there though..

**Comment by burnhamup** [comment]
I solved this part of the problem. It looks like emscripten has moved around some of their files. I had to edit config.mk to point the SDL include to `~/emscripten/system/include/SDL`. Maybe something needs to be updated in the makefile.
