### ISSUE TITLE
Stepping on plank outside Scumm Bar Kitchen

### ISSUE THREAD

**Issue by JamieMason** [juj/emscripten-scummvm#4]
Tried this twice in Chrome on the Mac and once Guybrush steps on the plank he keeps stepping on it in an infinite loop.

(This is the best bug report I've ever had to write by the way, thanks!)

**Comment by juj** [comment]
Thanks for the report! :D

I noticed the same, will need to check whether that occurs in the native version of the Monkey Island 1 demo.

**Comment by juj** [comment]
I ran the monkey1 demo in the native version of ScummVM on Windows, and it looks like it exhibits the same property, that Guybrush keeps stepping on the plank. However it is possible to give a new command to Guybrush and walk away from the plank in both native and web versions, so I think this bug should go to scummvm upstream instead.

**Comment by juj** [comment]
Closing, since this is not really an issue in emscripten-scummvm itself.
